#pragma once

#include "parser/csv_parser/csv_parser.h"

namespace tests {
extern CSVConfig const kWDC_astronomical;
extern CSVConfig const kWDC_symbols;
extern CSVConfig const kWDC_science;
extern CSVConfig const kWDC_satellites;
extern CSVConfig const kWDC_appearances;
extern CSVConfig const kWDC_astrology;
extern CSVConfig const kWDC_game;
extern CSVConfig const kWDC_kepler;
extern CSVConfig const kWDC_planetz;
extern CSVConfig const kWDC_age;
extern CSVConfig const kTestWide;
extern CSVConfig const kabalone;
extern CSVConfig const kiris;
extern CSVConfig const kadult;
extern CSVConfig const kbreast_cancer;
extern CSVConfig const kCIPublicHighway10k;
extern CSVConfig const kneighbors10k;
extern CSVConfig const kneighbors50k;
extern CSVConfig const kneighbors100k;
extern CSVConfig const kCIPublicHighway700;
extern CSVConfig const kEpicVitals;
extern CSVConfig const kEpicMeds;
extern CSVConfig const kiowa1kk;
extern CSVConfig const kfd_reduced_30;
extern CSVConfig const kflight_1k;
extern CSVConfig const kplista_1k;
extern CSVConfig const kletter;
extern CSVConfig const kCIPublicHighway;
extern CSVConfig const kLegacyPayors;
extern CSVConfig const kTestEmpty;
extern CSVConfig const kTestSingleColumn;
extern CSVConfig const kTestLong;
extern CSVConfig const kTestFD;
extern CSVConfig const kIndTestWide2;
extern CSVConfig const kIndTestEmpty;
extern CSVConfig const kIndTestPlanets;
extern CSVConfig const kIndTest3aryInds;
extern CSVConfig const kIndTestTableFirst;
extern CSVConfig const kIndTestTableSecond;
extern CSVConfig const kIndTestNulls;
extern CSVConfig const kTestZeros;
extern CSVConfig const kNullEmpty;
extern CSVConfig const kSimpleTypes;
extern CSVConfig const krules_book;
extern CSVConfig const krules_presentation_extended;
extern CSVConfig const krules_presentation;
extern CSVConfig const krules_synthetic_2;
extern CSVConfig const krules_kaggle_rows;
extern CSVConfig const ktennis;
extern CSVConfig const kmushroom;
extern CSVConfig const kTestDataStats;
extern CSVConfig const kTestMetric;
extern CSVConfig const kBernoulliRelation;
extern CSVConfig const kACShippingDates;
extern CSVConfig const kSimpleTypos;
extern CSVConfig const kTest1;
extern CSVConfig const kProbeTest1;
extern CSVConfig const kProbeTest2;
extern CSVConfig const kTestParse;
}  // namespace tests
