#pragma once

#include "core/algorithms/fd/aidfd/aid.h"
#include "core/algorithms/fd/depminer/depminer.h"
#include "core/algorithms/fd/dfd/dfd.h"
#include "core/algorithms/fd/dynfd/dynfd.h"
#include "core/algorithms/fd/eulerfd/eulerfd.h"
#include "core/algorithms/fd/fastfds/fastfds.h"
#include "core/algorithms/fd/fd_mine/fd_mine.h"
#include "core/algorithms/fd/fdep/fdep.h"
#include "core/algorithms/fd/fun/fun.h"
#include "core/algorithms/fd/hyfd/hyfd.h"
#include "core/algorithms/fd/pyro/pyro.h"
#include "core/algorithms/fd/sfd/cords.h"
#include "core/algorithms/fd/tane/pfdtane.h"
#include "core/algorithms/fd/tane/tane.h"
