name: Restore Datasets
description: Fetch hash and try to restore cache
inputs:
  github-token:
    description: "GitHub token used for authentication on GitHub. It is required when obtaining the sha of the latest
      commit in desbordante-data."
    required: true
outputs:
  hash:
    description: "Upstream commit SHA"
    value: ${{ steps.hash.outputs.sha }}
  cache-hit:
    description: "Cache hit status"
    value: ${{ steps.restore.outputs.cache-hit }}
runs:
  using: "composite"
  steps:
    - name: Get upstream hash
      id: hash
      shell: bash
      run: |
        echo ${{ inputs.github-token }} | gh auth login --with-token
        echo "sha=$(gh api repos/desbordante/desbordante-data/commits/HEAD --jq '.sha')" >> $GITHUB_OUTPUT

    - name: Restore cache
      id: restore
      uses: actions/cache/restore@v4
      with:
        path: datasets/*.zip
        key: datasets-${{ steps.hash.outputs.sha }}-1
