import desbordante as desb
import pandas as pd

LHS = 8
RHS = 9

PATH = 'examples/datasets/LineItem.csv'
SEP = '|'

BOLD = '\033[1m'
YELLOW = '\033[93m'
GREEN = '\033[92m'
DEFAULT = '\033[0m'

print(f"""{BOLD}{YELLOW}Preliminaries{DEFAULT}
Functional dependencies (FDs) are a classic concept in databases.
An FD is an expression X -> A, where X is a set of attributes, and A is an
attribute.

We call X "left-hand side" (LHS) and we call A "right-hand side" (RHS).
We say that an FD holds if we can determine the value of the RHS attribute
purely from the value of the LHS attributes.

However, for real-world data this requirement may be too strict. There are
several ways to relax it. In this example, you will be shown one of them.

We define an approximate functional dependency (AFD). Essentially, it lets some
LHS values not determine the RHS value. This is done by using an AFD measure
that determines "how strongly" an FD holds.

Strictly, we say that an AFD holds if its value is not below a threshold,
however, for this example, we will omit it and just use the output of the
various measures.""")
print()

print(f"""{BOLD}{YELLOW}AFD measures{DEFAULT}
An AFD measure takes an FD and data, returning a value in the [0, 1] range,
where 1 means the FD holds exactly, and values closer to 0 mean a weaker
dependency.

This also lets us speak of an inverse of the measure, referred to as an error,
which is just '1 - measure value'. The inverse of the error, conversely, is the
measure value.

Here we will showcase 8 different measures. These measures have been listed in
{BOLD}{GREEN}Measuring Approximate Functional Dependencies: a Comparative \
Study.{DEFAULT} by Marcel
Parciak, Sebastiaan Weytjens, Niel Hens, Frank Neven, Liesbet M. Peeters, Stijn
Vansummeren CoRR abs/2312.06296 (2023). If precise definitions are needed,
consult the article.

We've found that some measures are easier to explain through their corresponding
error values. The following measures are showcased:
- {GREEN}rho{DEFAULT}: the ratio of LHS values relative to the number of \
combined LHS and RHS
        values;
- {GREEN}pdep{DEFAULT}: probability that a random pair of records has equal \
RHS values, given it
        has equal LHS values;
- {GREEN}tau{DEFAULT} error: the probability that, when making two guesses \
about the RHS value
        of a randomly drawn tuple, one when not supplied information about its
        LHS values and one when we are, given that the former guess was
        incorrect, the latter one is incorrect as well;
- {GREEN}mu_plus{DEFAULT} error: tau error adjusted according to the number of \
records and the
        number of unique LHS values (increased when there are many unique
        values);
- {GREEN}fi{DEFAULT} error: how much uncertainty (as measured by Shannon \
entropy) is left about
        the RHS values once the LHS values have been supplied;
- {GREEN}g1{DEFAULT} error: the share of record pairs that show an FD violation;
- {GREEN}g2{DEFAULT} error: the share of records that participate in a \
violating pair;
- {GREEN}g3{DEFAULT} error: the minimum share of records that need to be taken \
out for the FD to
        hold.""")
print()

print(f"""{BOLD}{YELLOW}Data context{DEFAULT}
For the purposes of demonstration, we are going to use a "LINEITEM" table
similar to what would be generated using DBGen. DBGen is part of the decision
support benchmark called TPC-H. A line item table generated by it models a
plausible database table tracking the statuses of various shipments.

{GREEN}Table sample{DEFAULT}
Here is a sample of the records:""")
print()

DEMONSTRATION_COLUMNS = ['ORDERKEY', 'RETURNFLAG', 'LINESTATUS', 'SHIPDATE',
                         'RECEIPTDATE', 'SHIPMODE']
DEMONSTRATION_ROW_INDICES = [0, 1, 2, 3, 10, 100, 101, 102, 500, 533, 534, 535]
df = pd.read_csv(PATH, header=0, sep=SEP)
print(df[DEMONSTRATION_COLUMNS].iloc[DEMONSTRATION_ROW_INDICES].to_string(
    index=False))
print()
print("""SHIPDATE here represents the date shipping started, with RECEIPTDATE \
being
the date an item was or is projected to be received.\n""")

print(f'{GREEN}RETURNFLAG and LINESTATUS values{DEFAULT}')
print("""Let's take a closer look at two other columns: RETURNFLAG and \
LINESTATUS. We
will inspect their value distributions.""")

lhs_value_counts = df[df.columns[LHS]].value_counts()
print()
print(lhs_value_counts.to_string(dtype=False, length=False))
print()
print("""If an item has the value "N" in this column, we can interpret that it \
was "not
received" (though shipping may have started). "A" here means the item was
"accepted" (i.e. received and not returned) and "R" means the item was (received
and) "returned".""")
print()

rhs_value_counts = df[df.columns[RHS]].value_counts()
print(rhs_value_counts.to_string(dtype=False, length=False))
print()
print("""For LINESTATUS, "O" can be interpreted as "open" (not shipped yet), \
and
"F" can be interpreted as "fulfilled" (shipping started).""")
print()

print(f"""{BOLD}{YELLOW}Relationiship between RETURNFLAG and LINESTATUS{DEFAULT}
This data contains an AFD [RETURNFLAG] -> LINESTATUS. Suppose we found it during
AFD discovery and selected it for further examination. As part of it, we could
calculate AFD measure values to get an idea of "how" it holds and what it might
mean. Let's take a look at what various measures output:\n""")

calc = desb.afd_metric_calculation.algorithms.AFDMetricCalculator()
calc.load_data(table=(PATH, SEP, True))
measure_values = {}

for measure in ['rho', 'pdep', 'tau', 'mu_plus', 'fi', 'g1', 'g2', 'g3']:
    calc.execute(lhs_indices=[LHS], rhs_indices=[RHS], metric=measure)
    value = calc.get_result()
    print(f'{GREEN}{measure}{DEFAULT} = {value:.6f}')
    measure_values[measure] = value
print()

print('Notice that none of them return 1, but many are quite close, >0.95.')
print()

print("""We see the value for g2 being much lower than the others, with rho's \
value
also being considerably lower than 0.95. This tells us that while other measures
indicate that there is some kind of dependency, there are many pairs where the
exact FD is violated. Meanwhile, we know that there are three values in the
RETURNFLAG column, and the value for rho is exactly 3 / 4, which means that
there are only four combinations of RETURNFLAG and LINESTATUS.\n""")

print(f"""{YELLOW}{BOLD}Examining combined values{DEFAULT}
Since there are only four value combinations, we can take a look at exactly
what they are:""")

combined_value_counts = df[[df.columns[LHS], df.columns[RHS]]].value_counts()
print()
print(combined_value_counts.to_string(dtype=False, length=False))
print()

print("""We see that there is a single uncommon "N" and "F" combination. If \
"N"
means the item has been neither returned nor accepted, and "F" means that
shipping started, then the combination means the shipping is ongoing but the
item has not arrived at the destination, i.e. it is in transit.

The other combinations mean that either the item is still in the warehouse ("N"
and "O") or that it has already been received. Therefore, in this table, most
items are denoted to not be in transit, which is about what we would expect from
a slice of data representing recent deliveries.\n""")


print(f"""{YELLOW}{BOLD}An explanation of the measure values{DEFAULT}
For educational purposes, let's try to roughly explain why the measure values
ended up being what they are, in accordance with the explanations given at the
start.

{GREEN}g2{DEFAULT} (measure value is {measure_values['g2']:.6f}, error is \
{1 - measure_values['g2']:.6f})
Firstly, the g2 measure reports a value around 50% because most records (i.e.
all that have the "N" return flag) participate in a violating pair, with the
precise error value being {1 - measure_values['g2']:.6f}. The g2 measure's \
criterion ends up being far
too strict for this case.

{GREEN}rho{DEFAULT} (measure value is {measure_values['rho']:.6f})
The rho measure has already been explained. This measure only takes into account
how many unique value combinations there are, and with there being \
{len(lhs_value_counts)} RETURNFLAG
values, and {len(combined_value_counts)} possible combinations of RETURNFLAG \
and LINESTATUS, the measure's
value is exactly the ratio.

{GREEN}g3{DEFAULT} (measure value is {measure_values['g3']:.6f}, error is \
{1 - measure_values['g3']:.6f})
Only three records need to be taken out for there to be an exact FD from
RETURNFLAG to LINESTATUS.

{GREEN}g1{DEFAULT} (measure value is {measure_values['g1']:.6f}, error is \
{1 - measure_values['g1']:.6f})
The share of violating record pairs is small.

{GREEN}fi{DEFAULT} (measure value is {measure_values['fi']:.6f}, error is \
{1 - measure_values['fi']:.6f})
When observing "A" and "R", we know the return flag is "F", and when observing
"N" we can be pretty confident that the return flag is "O".

{GREEN}pdep{DEFAULT} (measure value is {measure_values['pdep']:.6f})
When taking two records, if they have the same RETURNFLAG value, we know the
LINESTATUS for "A" and "R" is certainly "F". If RETURNFLAG for both is "N", it
is very likely that their LINESTATUS values are both "O", and there is also a
small chance that both records have "F" as their LINESTATUS.

{GREEN}tau{DEFAULT} (measure value is {measure_values['tau']:.6f}, error is \
{1 - measure_values['tau']:.6f})
For the precise guess strategy, see the article. Basically, we guess a value X
with probability P if X's share is P.

There are two cases here.

Suppose we guessed LINESTATUS to be "O" and it is actually "F" (according to the
measure definition, we don't get to know that before the second guess). Then, if
we are supplied the information that RETURNFLAG's value is either "A" or "R", we
will know for certain that the value of LINESTATUS is "F". If RETURNFLAG's value
is "N", then we are likely to incorrectly guess the LINESTATUS value to be "O",
but this situation is quite rare.

On the other hand, suppose we guessed LINESTATUS to be "F" and it is actually
"O". Then we would be supplied RETURNFLAG "N" and are likely to guess LINESTATUS
to be "O" and be correct.

Thus, the probability of the second guess remaining incorrect is quite low, so
the measure's value ends up being high.

{GREEN}mu_plus{DEFAULT} (measure value is {measure_values['mu_plus']:.6f}, \
error is {1 - measure_values['mu_plus']:.6f})
There are only three unique values of RETURNFLAG with there being {len(df)} \
records,
thus the tau error is barely adjusted.\n""")

print(f"""{YELLOW}{BOLD}Additional information{DEFAULT}
Just like FDs, there can be multiple columns in the LHS. In that case the
measures treat the LHS as if it was a single column that combined the values of
the specified ones. Adding more columns can refine the dependency and increase
AFD measure values.\n""")

print(f"""{YELLOW}{BOLD}Other examples{DEFAULT}
- Discovering AFDs automatically.
    {GREEN}examples/basic/mining_afd.py{DEFAULT}
- Discovering exact FDs.
    {GREEN}examples/basic/mining_fd.py{DEFAULT}
- Checking if FDs hold and inspecting violations.
    {GREEN}examples/basic/verifying_fd_afd.py{DEFAULT}
- Discovering CFDs (another way to generalize FDs).
    {GREEN}examples/basic/mining_cfd.py{DEFAULT}""")

