name: 'Download datasets'
description: 'Download datasets'
runs:
  using: 'composite'
  steps:
  - name: Cache datasets
    uses: actions/cache@v3
    id: cache-datasets
    with:
      path: '${{github.workspace}}/datasets/*.zip'
      key: ${{ runner.os }}-datasets-${{ hashFiles('datasets/*.zip') }}