name: clang-format
on: [push, pull_request]
jobs:
  formatting-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: check-formatting
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y clang-format 
        formatterOutput=$(git clang-format --diff HEAD~1 HEAD)
        if [ "$formatterOutput" != "clang-format did not modify any files" ] &&
           [ "$formatterOutput" != "no modified files to format" ]
        then
          echo "$formatterOutput"
          exit 1
        fi
        
        echo "$formatterOutput"
