name: clang-format
on: [pull_request]
jobs:
  clang-format-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Pull clang-format
      run: |
        sudo apt-get update
        sudo apt-get install -y clang-format-12

    - name: Check formatting
      run: |       
        formatterOutput=$(git diff origin/$GITHUB_BASE_REF...origin/$GITHUB_HEAD_REF | clang-format-diff-12 -p 1)
        
        if [ "$formatterOutput" != "" ]
        then
          echo ":x: :x: :x:" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`c++" >> $GITHUB_STEP_SUMMARY
          echo "$formatterOutput" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
          echo "$formatterOutput"
          exit 1
        fi
        
        echo "$formatterOutput"
        echo "### $formatterOutput :heavy_check_mark:" >> $GITHUB_STEP_SUMMARY
  clang-tidy-check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: ZedThree/clang-tidy-review@v0.10.0
      id: review
      with:
        cmake_command: cmake . -DCMAKE_EXPORT_COMPILE_COMMANDS=on 
    # If there are any comments, fail the check
    - if: steps.review.outputs.total_comments > 0
      run: exit 1
