name: clang-format
on: [pull_request]
jobs:
  clang-format-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Pull clang-format
      run: |
        sudo apt-get update
        sudo apt-get install -y clang-format-12
    - name: Check formatting
      run: |       
        formatterOutput=$(git diff origin/$GITHUB_BASE_REF...origin/$GITHUB_HEAD_REF | clang-format-diff-12 -p 1)
        
        if [ "$formatterOutput" != "" ]
        then
          echo ":x: :x: :x:" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`c++" >> $GITHUB_STEP_SUMMARY
          echo "$formatterOutput" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
          echo "$formatterOutput"
          exit 1
        fi
        
        echo "$formatterOutput"
        echo "### $formatterOutput :heavy_check_mark:" >> $GITHUB_STEP_SUMMARY
  clang-tidy-check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Cache Boost
      uses: actions/cache@v2
      id: cache-boost
      with:
        path: ${{github.workspace}}/lib/boost
        key: ${{ runner.os }}-boost
    - name: Install Boost
      run: |
        wget -O boost_1_72_0.tar.gz https://sourceforge.net/projects/boost/files/boost/1.72.0/boost_1_72_0.tar.gz/download
        tar xzvf boost_1_72_0.tar.gz
        cd boost_1_72_0
        ./bootstrap.sh --prefix=${{github.workspace}}/lib/boost
        ./b2
        sudo ./b2 install
      if: steps.cache-boost.outputs.cache-hit != 'true'
    - name: Generate compile_commands.json
      uses: lukka/run-cmake@v3
      with:
        cmakeListsOrSettingsJson: CMakeListsTxtAdvanced
        cmakeListsTxtPath: '${{github.workspace}}/CMakeLists.txt'
        useVcpkgToolchainFile: true
        # has to be the github workspace, not the runner workspace, for the docker-based clang-tidy-review
        buildDirectory: '${{github.workspace}}/build'
        cmakeAppendedArgs: >-
          -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
        buildWithCMakeArgs: >-
          --target autogen
    - name: Get DEBUG info
      run: |
        cmake --version
    - uses: ZedThree/clang-tidy-review@v0.10.0
      id: review
      with:
        build_dir: build
#         cmake_command: cmake -DBOOST_ROOT=${{github.workspace}}/lib/boost . -B build -DCMAKE_EXPORT_COMPILE_COMMANDS=on 
    # If there are any comments, fail the check
    #- if: steps.review.outputs.total_comments > 0
    #  run: exit 1
    - name: Get DEBUG info2
      run: |
        cat /github/workspace/CMakeFiles/CMakeOutput.log compile_commands.json
      if: always()
        
