name: CMake
on:
  pull_request:
    types: [opened, edited, synchronize, reopened, labeled]
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  run_tests: 
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        BUILD_TYPE: [ Release, Debug ]
    steps:
    - uses: actions/checkout@v2
    - name: Install build tools
      run: |
        sudo apt-get update
        sudo apt-get install gcc-10 g++-10 cmake build-essential
    - name: Cache Boost
      uses: actions/cache@v2
      id: cache-boost
      with:
        path: ${{github.workspace}}/lib/boost
        key: ${{ runner.os }}-boost
    - name: Cache googletest
      uses: actions/cache@v2
      id: cache-googletest
      with:
        path: ${{github.workspace}}/lib/googletest
        key: ${{ runner.os }}-googletest
    - name: Cache easyloggingpp
      uses: actions/cache@v2
      id: cache-easyloggingpp
      with:
        path: ${{github.workspace}}/lib/easyloggingpp
        key: ${{ runner.os }}-easyloggingpp
    - name: Install git-lfs
      run: |
        curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | sudo bash
        git lfs install
    - name: Generate lfs file list
      run: git lfs ls-files -l | cut -d' ' -f1 | sort > .lfs-assets-id
    - name: Restore lfs cache
      uses: actions/cache@v2
      id: lfs-cache
      with:
        path: .git/lfs
        key: ${{ runner.os }}-lfs-${{ hashFiles('.lfs-assets-id') }}-v1
    - name: Pull lfs files
      run: git lfs pull
    - name: Install Boost
      run: |
        wget -O boost_1_72_0.tar.gz https://sourceforge.net/projects/boost/files/boost/1.72.0/boost_1_72_0.tar.gz/download
        tar xzvf boost_1_72_0.tar.gz
        cd boost_1_72_0
        ./bootstrap.sh --prefix=${{github.workspace}}/lib/boost
        ./b2
        sudo ./b2 install
      if: steps.cache-boost.outputs.cache-hit != 'true'
    - name: Download googletest
      run: |
        mkdir -p lib
        sudo chown -R $USER lib 
        cd lib
        git clone https://github.com/google/googletest/ --branch release-1.10.0
      if: steps.cache-googletest.outputs.cache-hit != 'true'
    - name: Download easyloggingpp
      run: |
        mkdir -p lib
        sudo chown -R $USER lib
        cd lib
        git clone https://github.com/amrayn/easyloggingpp/ --branch v9.97.0
      if: steps.cache-easyloggingpp.outputs.cache-hit != 'true'
    - name: Configure CMake
      run: >
        cmake -B ${{github.workspace}}/build
        -DCMAKE_C_COMPILER=gcc-10
        -DCMAKE_CXX_COMPILER=g++-10
        -DBOOST_ROOT=${{github.workspace}}/lib/boost
        -DCMAKE_BUILD_TYPE=${{matrix.BUILD_TYPE}}
        -Dgtest_disable_pthreads=OFF
    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{matrix.BUILD_TYPE}}
    - name: Test
      working-directory: ${{github.workspace}}/build/target
      shell: bash
      run: ./Desbordante_test --gtest_filter='*:-*HeavyDatasets*'
