name: CMake
on: [push]
env:
  BUILD_TYPE: Release
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Install build tools
      run: |
        sudo apt-get update
        sudo apt-get install build-essential g++ cmake
    - name: Cache Boost
      uses: actions/cache@v2
      id: cache-boost
      with:
        path: /usr/boost
        key: ${{ runner.os }}-boost
    - name: Cache googletest
      uses: actions/cache@v2
      id: cache-googletest
      with:
        path: ~/lib/googletest
        key: ${{ runner.os }}-googletest
    - name: Install Boost
      run: |
        wget -O boost_1_65_1.tar.gz https://sourceforge.net/projects/boost/files/boost/1.65.1/boost_1_65_1.tar.gz/download
        tar xzvf boost_1_65_1.tar.gz
        cd boost_1_65_1
        ./bootstrap.sh --prefix=/usr/boost
        ./b2
        sudo ./b2 install
      if: steps.cache-boost.outputs.cache-hit != 'true'
    - name: Download googletest
      run: |
        mkdir lib
        cd lib
        git clone https://github.com/google/googletest/ --branch release-1.10.0
      if: steps.cache-googletest.outputs.cache-hit != 'true'
    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DBOOST_ROOT=/usr/boost/
    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
