name: CMake
on: [push]
env:
  BUILD_TYPE: Release
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install build-essential g++ python-dev autotools-dev libicu-dev libbz2-dev libboost-all-dev
    - name: Download Boost
      run: |
        wget -O boost_1_65_1.tar.gz https://sourceforge.net/projects/boost/files/boost/1.65.1/boost_1_65_1.tar.gz/download
        tar xzvf boost_1_65_1.tar.gz
    - name: Install Boost
      run: |
        cd boost_1_65_1
        ./bootstrap.sh --prefix=/usr/
        ./b2
        sudo ./b2 install
    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
