name: CMake
on: [push]
env:
  BUILD_TYPE: Release
jobs:
  setup:
    runs-on: ubuntu-18.04
    steps:
    - name: Install dependencies
      run: |
        apt-get update
        apt-get install build-essential g++ python-dev autotools-dev libicu-dev libbz2-dev libboost-all-dev
    - name: Download Boost
      run: |
        wget -O boost_1_65_1.tar.gz https://sourceforge.net/projects/boost/files/boost/1.55.0/boost_1_55_0.tar.gz/download
        tar xzvf boost_1_65_1.tar.gz
        cd boost_1_65_1
    - name: Install Boost
      run: |
        ./bootstrap.sh --prefix=/usr/
        ./b2
        ./b2 install
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name:
    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
